setup: |
  echo "TODO: Set Up Dependencies"
  echo "installed all dependencies."
---

# check the main file
- ostop/main.py:
    - description: Use the schedule library
      check: MatchFileFragment
      options:
        fragment: import schedule
        count: 1
        exact: true
    - description: Check the os using platform.system()
      check: MatchFileFragment
      options:
        fragment: platform.system()
        count: 1
        exact: false

# check the mac file
- ostop/mac.py:
    - description: Use the psutil library
      check: MatchFileFragment
      options:
        fragment: import psutil
        count: 1
        exact: true
    - description: Create sufficient single-line comments
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 25
        exact: false
    - description: Ensure the top function exists
      check: MatchFileFragment
      options:
        fragment: top()
        count: 1
        exact: false
    - description: Ensure the process_stats function exists
      check: MatchFileFragment
      options:
        fragment: process_stats()
        count: 1
        exact: false

# check the windows file
- ostop/windows.py:
    - description: Use the psutil library
      check: MatchFileFragment
      options:
        fragment: import psutil
        count: 1
        exact: true
    - description: Create sufficient single-line comments
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 25
        exact: false
    - description: Ensure the top function exists
      check: MatchFileFragment
      options:
        fragment: top()
        count: 1
        exact: false
    - description: Ensure the process_stats function exists
      check: MatchFileFragment
      options:
        fragment: process_stats()
        count: 1
        exact: false

# check the linux file
- ostop/linux.py:
    - description: Use the psutil library
      check: MatchFileFragment
      options:
        fragment: import psutil
        count: 1
        exact: true
    - description: Create sufficient single-line comments
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 25
        exact: false
    - description: Ensure the top function exists
      check: MatchFileFragment
      options:
        fragment: top()
        count: 1
        exact: false
    - description: Ensure the process_stats function exists
      check: MatchFileFragment
      options:
        fragment: process_stats()
        count: 1
        exact: false

# run the program using a single run
- description: Run top for one iteration and ensure it does not crash.
  command: python ostop/main.py 1
