name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: ["3.10"]

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Markdown Linting
        if: matrix.os == 'ubuntu-latest'
        uses: actionshub/markdownlint@main
      - name: Setup Python ${{ matrix.python-version }}
        if: always()
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        if: always()
        run:  |
            pip install gatorgrade
            pip install ostop
      - name: Run GatorGrader with GatorGrade
        if: matrix.os == 'ubuntu-latest'
        run:  |
            gatorgrade --config config/gatorgrade.yml
      - name: Run top once
        if: always()
        run:  |
            ostop 1
      - name: Run top twice
        if: always()
        run:  |
            ostop 2
